### ISSUE TITLE
Weird long help output

### ISSUE THREAD

**Issue by dupgit** [ayosec/bash-builtins.rs#4]
Hi,

I'm using ` builtin_metadata!()` macro from `bash-builtins = "0.3.1"` and its `short_doc` and `long_doc` options:
```rust
builtin_metadata!(
    name = "cpubind",
    create = CpuBind::default,
    short_doc = "cpubind [-i identifier]",
    long_doc = "
    Prints information about the task and it's cpu affinity

    Options:
        -i identifier used to identify that particular task
    ",
);

#[derive(BuiltinOptions)]
enum Opt {
    #[opt = 'i']
    Identifier(String),
}
```

With this as is, when I invoke bash help command I get:
```bash
$  help cpubind 
cpubind: cpubind [-i identifier]
    Prints information about the task and it's cpu affinity
    Project-Id-Version: bash-5.2-rc1
Report-Msgid-Bugs-To: 
PO-Revision-Date: 2022-06-19 10:44+0200
Last-Translator: Frédéric Marchal <fmarchal@perso.be>
Language-Team: French <traduc@traduc.org>
Language: fr
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
X-Bugs: Report translation errors to the Language-Team address.
Plural-Forms: nplurals=2; plural=(n >= 2);

    Options:
        -i identifier used to identify that particular task
```

If I just delete the blank line in `long_doc` variable I get:
```bash
$  help cpubind 
cpubind: cpubind [-i identifier]
    Prints information about the task and it's cpu affinity
    Options:
        -i identifier used to identify that particular task

```

It seems that blank lines without any blank spaces are replaced by some other text that may be available somehow in the memory. I managed to get it work correctly using a non-breaking white character to keep the alignment and a non blank line (my editor won't let me save a blank line).
The whole code is available at https://github.com/dupgit/cpubind-bash-builtin.

**Comment by ayosec** [comment]
I tested <https://github.com/dupgit/cpubind-bash-builtin>, after removing the line with the non-breaking space, but I can't reproduce the issue:

```console
$ LC_ALL=C git diff
diff --git a/src/lib.rs b/src/lib.rs
index 9e42efc..fc4f1f8 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -12,7 +12,7 @@ builtin_metadata!(
     // prints other lines from bash's memory instead.
     long_doc = "
     Prints information about the task and it's cpu affinity
-    <C2><A0>
+
     Options:
         -i identifier used to identify that particular task
     ",

$ cargo build --release

$ enable -f target/release/libcpubind_bash_builtin.so cpubind

$ help cpubind
cpubind: cpubind [-i identifier]
    Prints information about the task and it's cpu affinity
     
    Options:
        -i identifier used to identify that particular task
```

I tested it against Bash 5.2.15 (Debian Stable) and 5.2.26 (Nix unstable), both with Rust 1.76.

What environment are you using?

---

As you said, the problem is that Bash is reading memory from another place. Bash expects the `long_doc` field as an array of strings (one item per line). An empty line should be just `"\0"`, which seems to be problematic in the Bash version you are using.

[`cargo expand`](https://github.com/dtolnay/cargo-expand) can be used to check the generated output:

```console
$ cargo expand
```

```rust
// ...
pub static mut cpubind_struct: ::bash_builtins::ffi::BashBuiltin =
    ::bash_builtins::ffi::BashBuiltin {
        name: "cpubind\u{0}".as_ptr().cast(),
        function: __bash_builtin__func_cpubind,
        flags: ::bash_builtins::ffi::flags::BUILTIN_ENABLED,
        short_doc: "cpubind [-i identifier]\u{0}".as_ptr().cast(),
        long_doc: (&[
            "Prints information about the task and it's cpu affinity\u{0}".as_ptr().cast(),
            "\u{0}".as_ptr().cast(),
            "Options:\u{0}".as_ptr().cast(),
            "    -i identifier used to identify that particular task\u{0}".as_ptr().cast(),
            ::std::ptr::null(),
        ]).as_ptr(),
```

Without debugging, the only explanation I can see is that Bash is ignoring the `\0` character if it is at the beginning of the line.

**Comment by dupgit** [comment]
Hi, thanks for taking the time to look at this. I think I have found what causes this behavior thanks to your remarks:

I use bash 5.2.15 from debian bookworm (stable):
```bash
$ bash --version
GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2022 Free Software Foundation, Inc.
Licence GPLv3+ : GNU GPL version 3 ou ultérieure <http://gnu.org/licenses/gpl.html>

Ceci est un logiciel libre ; vous être libre de le modifier et de le redistribuer.
AUCUNE GARANTIE n'est fournie, dans les limites permises par la loi.
```

Note that the license is translated in French. I should have noticed that from my first message as the inserted message is somehow a .po translation file header. 
Invoking bash help command with C LANG does not reproduce the problem:
```bash
$  LANG=C help cpubind
cpubind: cpubind [-i identifier]
    Prints information about the task and it's cpu affinity
    
    Options:
        -i identifier used to identify that particular task
```
The problem seems to happen with any locale:
```
$ LANG=es_ES.UTF-8 help cpubind
cpubind: cpubind [-i identifier]
    Prints information about the task and it's cpu affinity
    Project-Id-Version: bash-5.2-rc1
Report-Msgid-Bugs-To: 
PO-Revision-Date: 2022-06-19 10:44+0200
Last-Translator: Frédéric Marchal <fmarchal@perso.be>
Language-Team: French <traduc@traduc.org>
Language: fr
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
X-Bugs: Report translation errors to the Language-Team address.
Plural-Forms: nplurals=2; plural=(n >= 2);

    Options:
        -i identifier used to identify that particular task
```

May be bash behavior is different in that case because it is trying to find a translation for the `long_doc` in the specified locale ?
Indeed invoking help command on `bind` builtin gives me an help message in French !

**Comment by ayosec** [comment]
That must be the problem.

The [gettext documentation](https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html) seems to confirm that empty strings must not be used here:

> An empty `untranslated-string` is reserved to contain the header entry with the meta information (see [Filling in the Header Entry](https://www.gnu.org/software/gettext/manual/html_node/Header-Entry.html)). This header entry should be the first entry of the file. The empty `untranslated-string` is reserved for this purpose and must not be used anywhere else.

So the crate must not generate empty strings in the array of the `long_doc` field.

---

Built-ins in the Bash sources are defined in a very particular way:

* Built-ins are implemented in `.def` files.

    These are regular C files, with some special directives to define the metadata, like `$BUILTIN` or `$SHORT_DOC`.

    After `$END`, the file contains the implementation for that directive until another `$BUILTIN` (or EOF) is found.

    For example, [`break.def`](https://git.savannah.gnu.org/cgit/bash.git/tree/builtins/break.def?h=bash-5.2) defines `break` like this:

    ```
    $BUILTIN break
    $FUNCTION break_builtin
    $SHORT_DOC break [n]
    Exit for, while, or until loops.

    Exit a FOR, WHILE or UNTIL loop.  If N is specified, break N enclosing
    loops.

    Exit Status:
    The exit status is 0 unless N is not greater than or equal to 1.
    $END

    // C code
    ```

* A preprocessor implemented in [`mkbuiltins.c`](https://git.savannah.gnu.org/cgit/bash.git/tree/builtins/mkbuiltins.c?h=bash-5.2) reads the `.def` files and generates the final C code.

When I wrote the initial version of this crate I assumed that each line of the documentation was in its own array element; but I just checked the generated C file, and it is writing a single string with the whole documentation. For example, for `break`:

```c
char * const break_doc[] = {
#if defined (HELP_BUILTIN)
N_("Exit for, while, or until loops.\n\
    \n\
    Exit a FOR, WHILE or UNTIL loop.  If N is specified, break N enclosing\n\
    loops.\n\
    \n\
    Exit Status:\n\
    The exit status is 0 unless N is not greater than or equal to 1."),
#endif /* HELP_BUILTIN */
  (char *)NULL
};
```

In that snippet, `N_` is just a gettext macro to indicate that the string can be translated.

I changed the implementation in a13dc2cff25c3a8860235b32d9f71a78e0d5afda. Now, the generated string is identical to what `mkbuiltins.c` is emitting.

I just released a new version of the crate. Can you test the version `0.4` to verify that the issue is fixed? Thanks!

**Comment by dupgit** [comment]
Thank you very much for this fix and release: it works like a charm :-)
Just corrected my own builtin https://github.com/dupgit/cpubind-bash-builtin/commit/693a330d5695b1dd5ea3a94cd308ece2e60d8414.

Thank you very much for this crate and your support.
